/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
 * Date:	June 18, 2021
 * Author:	Michael Ly
 * Details:	Turn on the LED of the target board
 * 			You will need knowledge of pointers, bitwise operations,
 * 			and hardware connections
 *
 * Note:	Check the project's directory for the address_calculation.txt
 * 			file
 */

#include <stdint.h>
#include <stdio.h>

extern void initialise_monitor_handles(void);

/* Constants */
const uint32_t	ADDR_RCC	= 0x40023830 ;					// Address of the RCC peripheral clock reg (AHB1ENR)
const uint32_t	ADDR_MODE	= 0x40021800 ;					// Address of GPIOG pin 13 (Green_LED)
const uint32_t	ADDR_OUT	= 0x40021814 ;					// Address of GPIOG output data register
const uint32_t	M_CLK_EN	= 1 << 6 ;						// Mask to set the 6th bit: clk enable
//const uint32_t	M_CLR_MODE	= 0xF3FFFFFF ;				// Test (&) everything with '1' except 26th and 27th bits
const uint32_t	M_CLR_MODE	= 3 << 26 ;						// Clears the 24th and 25th bits by shifting binary 3
//const uint32_t	M_SET_MODE	= 0x04000000 ;				// Set (|) everything with '0' except the 26th and 27th bits
const uint32_t	M_MODE_SET	= 1 << 26 ;						// Shorthand of above
const uint32_t	M_OUT_SET	= 1 << 13 ;						// SETs the 13th bit position of output data register

int main(void)
{
	initialise_monitor_handles();

	// Turn on the peripheral clock by setting enable high
	uint32_t *pClkCtrlReg	= (uint32_t*) ADDR_RCC ;		// Assign a pointer address for RCC
	uint32_t *pPortGModeReg	= (uint32_t*) ADDR_MODE ;		// Assign a pointer address for Port G Mode
	uint32_t *pPortGOutReg	= (uint32_t*) ADDR_OUT ;		// Assign a pointer address for Port G Out

	// 1.) Enable the clock for GPIOG peripheral in the AHB1ENR
	*pClkCtrlReg |= M_CLK_EN ;								// Set clk enable bit with mask

	// 2.) Configure the mode of the IO pin as output (01)
	// a.) Clear the 26th and 27th bit positions
	*pPortGModeReg &= ~M_CLR_MODE ;
	// b.) Make 26th bit position as 1 (SET)
	*pPortGModeReg |=  M_MODE_SET ;

	// Shorthand way to do the previous two steps since everything is set to 0 upon startup:
    // *pPortGModeReg |= M_MODE_SET ;							// SET the mode

	// 3.) SET the 13th bit of the output data register to make I/O pin-13 HIGH
	*pPortGOutReg |= M_OUT_SET ;

    /* Loop forever */
	while (1) ;
}
